services:
  mongodb:
    container_name: ws_mongo_db
    image: mongo
    ports:
      - 27016:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd
    restart: unless-stopped